### ISSUE TITLE
Align attributes with OpenTelemtery semantic conventions

### ISSUE THREAD

**Issue by pavolloffay** [weaveworks-experiments/kspan#46]
The added span attributes do not follow OTEL k8s resource attributes 

![Screenshot of Jaeger UI (2)](https://user-images.githubusercontent.com/5618424/144253439-ca1c83d4-9b9a-4c2d-91da-091dc7b43de6.jpg)

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/k8s.md

Using the same attributes consistently should help to correlate user workflow traces with k8s event traces.

**Comment by bboreham** [comment]
Happy to follow conventions, but I'm unclear what exactly you would change.  I don't see one at that URL for the generic name of an object.

I'm not happy to put any hard-coding of pods, etc., into Kspan.

**Comment by pavolloffay** [comment]
The idea here is to increase the correlation between traces emitted from various instrumentation. To make this happen instrumentations should use the same attributes names for the same data. 

There isn't a generic name for an object. Most likely we would have to use the kind name as part of the attribute name. Some attributes are easier e.g. the namespace.
