### ISSUE TITLE
I need acces to my @sales.weave.works

### ISSUE THREAD

**Issue by hermannngaina** [weaveworks-experiments/kspan#49]
I need a support request to have my your_username@sales.weave.works alias added to my Google Workspace account and get added to the access_salesloft_sso Google Group

**Comment by bboreham** [comment]
Sorry I don’t understand. 

Are you perhaps mistaken where you are asking?  This is an Open Source  tool for visualising Kubernetes events.

**Comment by morancj** [comment]
Yes, wrong repo. Closing.
