### ISSUE TITLE
What is the future of kspan?

### ISSUE THREAD

**Issue by TylerHelmuth** [weaveworks-experiments/kspan#57]
First off, thank you for making this concept a reality - turning k8s events into tracing is a truely powerful tool.  We (Honeycomb) love using this tool.  We love it so much that over the last two years we've been using a private fork as a means of quickly iterating on the project for our own internal needs.

We noticed this repository has grown cold, so when some of our customers wanted to try out this project we, liking the changes we added, published a version of this project over at https://github.com/honeycombio/kspan for them to use. [There is also revitalized interest in the OpenTelemetry community to add kspan's functionality to the OpenTelemetry Collector.](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7408)

With the increased interest in the project we are now reaching out asking "what is the future for kspan"?

If you would like to collaborate on this project, we are interested in working on it actively, starting right away. If you're no longer interested, we'd appreciate it if you archived this and added a pointer to [our fork](https://github.com/honeycombio/kspan).

**Comment by bboreham** [comment]
Thanks; I do think about Kspan quite often but personally have been focused on some other things for the past couple of years.

Since I get hundreds of GitHub notifications it's better to mention me personally if you want to catch my attention.
